### PR TITLE
FPS-105: Fix broken links (and other minor fixes)

### PR DESCRIPTION
**Pull request by myersadamk**
* Fixed broken links. I opted for absolute paths rather than relative paths, because links built with relative paths occasionally break when swapping between languages (not sure exactly what triggered this, but it's almost certainly a bug in the JS somewhere)
* Updated links to the zendesk site to point internally instead
* Added an ES translation for 'Overview of Kiva's API' (translation from Mateo)
* Adding firebase config (seems reasonable/good to have this in the repo; we can later automate firebase deployments)
* Deleted redundant `/en/` i18n directory: the default locale is English, so the default `/docs` path shows up as English in the dropdown (the code was copy/pasted and I spent a few minutes trying to figure out why my changes weren't getting picked up)

# Testing
[Preview deployment](https://fps-sdk-portal--preview-fps-105-ywxkhcyr.web.app/) is available! I created [FPS-117](https://kiva.atlassian.net/browse/FPS-117) to explore improvements we can make to the deployment process via GitHub actions.

I used the [firebase-cli to deploy locally](https://firebase.google.com/docs/hosting/test-preview-deploy).

From `/fps-sdk/portal`, run `yarn clear && yarn build`, and then run the firebase emulator as outlined in the README.

[FPS-117]: https://kiva.atlassian.net/browse/FPS-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by myersadamk** [comment]
> we cannot delete the en files. in order for translations to work within the docusaur toolset, the en files must exist even though our default pages are english.

@matt-raffel-kiva have you tested this? I tested with the firebase emulator it and it works. I'll be pretty disappointed if docusaurus requires us to copy/paste this directory.

**Comment by matt-raffel-kiva** [comment]
yes I have tested this...hence why I ask the files be added back

**Comment by matt-raffel-kiva** [comment]
>

**Comment by matt-raffel-kiva** [comment]
This PR was closed accidentally. I was trying to delete a comment.

**Review by matt-raffel-kiva — CHANGES_REQUESTED** [review]
lets remove all references to using yarn for testing (since we have how one will test with firebase).

**Review by matt-raffel-kiva — APPROVED** [review]

**Pull request merged**
